Ability to pass id prop to whole table
aminya/solid-simple-table pull request #16
Opened 2022-05-29 12:53 UTC by KamilRybacki

Hello!

Thanks for Your awesome library! :+1: 
I've been working with it lately and noticed that there wasn't a way to assing a global `id` attribute via `props` to the whole table, since it wasn't being deconstructed within `SimpleTable<Ind extends IndexType = IndexType>(props: Props<Ind>)` function in `SimpleTable.tsx`.

Therefore, I propose adding this feature since it is always awesome to be able to query things via unique `id`s e.g. during tests of DOM manipulations :smile: 

Lemme know if You agree with my idea and/or styling of this new section of code.

Best regards :pray:

2022-11-07 08:02 UTC, aminya requested changes
It would be great if you could add a test

2023-01-24 09:20 UTC, KamilRybacki commented
Hi! Thanks for replying, I've seem to have missed You comment due to some mishap in notifications. I have added the tests You have mentions, together with changes to demo tables & SimpleTable component, so that the id of the rendered elements id correctly passed thru props.

2023-01-24 23:12 UTC, aminya approved these changes
Thank you for adding the tests!

2023-01-24 23:13 UTC, aminya commented on src/SimpleTable.tsx
> +      className={props.className ?? "solid-simple-table light typography"}
```suggestion
      class={props.className ?? "solid-simple-table light typography"}
```

2023-01-24 23:17 UTC, merged